<a href="https://colab.research.google.com/github/xAlessox/docs/blob/main/ProyectoDS%26ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##----------------------------------------------------------------------------
##-----------------------------EJERCICIO 1------------------------------------
##----------------------------------------------------------------------------

In [ ]:
##EJERCICIO 1

"""Escribir un programa que pregunte al usuario o genere las ventas
de los últimos 5 días, y muestre por pantalla una serie (Dataframe)
con los datos de las ventas por producto (opcional): Nro de
unidades y precio unitario, indexada por los días, antes y después
de aplicarles un descuento del 5%."""

In [ ]:
##---------------------PARTE 1
"""Generar un obejto Series que presente las ventas de los últimos 5 días"""

In [28]:
##Solicitando al usuario las ventas de los últimos 5 días y almacenandolo en una lista

print("Ingrese las ventas de los últimos 5 días...\n")

venta_diaria = []

for dia in range(5):

  while True:

    try:
      print("Ingrese el monto total vendido en el día",dia+1,":")
      venta =(float(input()))

      if type(venta) == float and venta > 0:
        venta_diaria.append(venta)
        break
      else:
        print("Ingrese un valor válido")
    except:
      print("Ingrese un valor válido")

Ingrese las ventas de los últimos 5 días...

Ingrese el monto total vendido en el día 1 :
100.50
Ingrese el monto total vendido en el día 2 :
120
Ingrese el monto total vendido en el día 3 :
50
Ingrese el monto total vendido en el día 4 :
45.60
Ingrese el monto total vendido en el día 5 :
99.99

In [29]:
##Importando el paquete pandas

import pandas as pd

##Creando un objeto "Series" con los datos de las ventas de los últimos 5 días

series_ventadiaria = pd.Series(venta_diaria)
series_ventadiaria

0    100.50
1    120.00
2     50.00
3     45.60
4     99.99
dtype: float64

In [ ]:
##---------------------PARTE 2
"""Generar un dataframe con la información del: producto, precio unitario y precio unitario con descuento del 5%"""

In [30]:
##Registrando la información del producto, precio unitario

print("Ingrese la información de venta de los productos vendidos en los últimos 5 días...\n")

while True:
  try:
    distinct_producto = int(input("¿Cuantos productos diferentes vendió?: "))
    if type(distinct_producto) == int and distinct_producto > 0:
      break
    else:
      print("Ingrese un valor válido")5
  except:
    print("Ingrese un valor válido")

lproducto = []
lprecio_producto = []
lventa_producto = []
lventa_dias = []

for counter_producto in range(distinct_producto):
  lventa_dias = []


  print("\n---PRODUCTO",counter_producto+1)
  producto = input("Ingrese el nombre del producto: ")
  lproducto.append(producto)

  while True:
    try:
      precio = float(input("Ingrese el precio unitario del producto: "))
      if type(precio) == float and precio > 0:
        lprecio_producto.append(precio)
        break
      else:
        print("Ingrese un precio válido")
    except:
      print("Ingrese un precio válido")

  for dia in range(5):
    print("\nIngrese la cantidad del producto",producto,"vendida...")
    print("Dia",dia+1,":")

    while True:
      try:
        venta_dia = int(input())
        if type(venta_dia) == int and venta_dia >=0:
          lventa_dias.append(venta_dia)
          break
        else:
          print("Ingrese una cantidad válida")
      except:
        print("Ingrese una cantidad válida")

  lventa_producto.append(lventa_dias)

print()
print(lproducto)
print(lprecio_producto)
print(lventa_producto)

Ingrese la información de venta de los productos vendidos en los últimos 5 días...

¿Cuantos productos diferentes vendió?: 4

---PRODUCTO 1
Ingrese el nombre del producto: Coco
Ingrese el precio unitario del producto: dos
Ingrese un precio válido
Ingrese el precio unitario del producto: -10
Ingrese un precio válido
Ingrese el precio unitario del producto: 1

Ingrese la cantidad del producto Coco vendida...
Dia 1 :
5

Ingrese la cantidad del producto Coco vendida...
Dia 2 :
6

Ingrese la cantidad del producto Coco vendida...
Dia 3 :
0

Ingrese la cantidad del producto Coco vendida...
Dia 4 :
8

Ingrese la cantidad del producto Coco vendida...
Dia 5 :
10

---PRODUCTO 2
Ingrese el nombre del producto: Papaya
Ingrese el precio unitario del producto: 2.25

Ingrese la cantidad del producto Papaya vendida...
Dia 1 :
2

Ingrese la cantidad del producto Papaya vendida...
Dia 2 :
4

Ingrese la cantidad del producto Papaya vendida...
Dia 3 :
0

Ingrese la cantidad del producto Papaya vendida...
Dia 4 :
0

Ingrese la cantidad del producto Papaya vendida...
Dia 5 :
1

---PRODUCTO 3
Ingrese el nombre del producto: Melon
Ingrese el precio unitario del producto: 1.50

Ingrese la cantidad del producto Melon vendida...
Dia 1 :
2

Ingrese la cantidad del producto Melon vendida...
Dia 2 :
3

Ingrese la cantidad del producto Melon vendida...
Dia 3 :
4

Ingrese la cantidad del producto Melon vendida...
Dia 4 :
5

Ingrese la cantidad del producto Melon vendida...
Dia 5 :
3

---PRODUCTO 4
Ingrese el nombre del producto: Sandia
Ingrese el precio unitario del producto: 2

Ingrese la cantidad del producto Sandia vendida...
Dia 1 :
10

Ingrese la cantidad del producto Sandia vendida...
Dia 2 :
8

Ingrese la cantidad del producto Sandia vendida...
Dia 3 :
6

Ingrese la cantidad del producto Sandia vendida...
Dia 4 :
5

Ingrese la cantidad del producto Sandia vendida...
Dia 5 :
4

['Coco', 'Papaya', 'Melon', 'Sandia']
[1.0, 2.25, 1.5, 2.0]
[[5, 6, 0, 8, 10], [2, 4, 0, 0, 1], [2, 3, 4, 5, 3], [10, 8, 6, 5, 4]]

In [31]:
##Importando los paquetes numpy y pandas

import numpy as np
import pandas as pd

##Creando un array para:
##*la lista de ventas por producto para luego poder separarlas en las columnas del dataframe
##*la lista de precio con el descuento del 5% aplicado

np_lventa_producto = np.array(lventa_producto)
np_lprecio_producto = np.array(lprecio_producto) * 0.95

##Generando el dataframe

data = {'Producto':lproducto,'Precio':lprecio_producto,'Precio w/disc:':np_lprecio_producto,
        'Dia1':np_lventa_producto[:,0],'Dia2':np_lventa_producto[:,1],'Dia3':np_lventa_producto[:,2],
        'Dia4':np_lventa_producto[:,3],'Dia5':np_lventa_producto[:,4]}

df_resumen_ventas = pd.DataFrame(data)
df_resumen_ventas

  Producto  Precio  Precio w/disc:  Dia1  Dia2  Dia3  Dia4  Dia5
0     Coco    1.00          0.9500     5     6     0     8    10
1   Papaya    2.25          2.1375     2     4     0     0     1
2    Melon    1.50          1.4250     2     3     4     5     3
3   Sandia    2.00          1.9000    10     8     6     5     4

In [ ]:
##----------------------------------------------------------------------------
##-----------------------------EJERCICIO 2------------------------------------
##----------------------------------------------------------------------------

In [ ]:
"""Escribir un programa que reciba un diccionario con los ingresos
mensuales de los clientes de una empresa, y devuelva una serie
con el ingreso mínimo, máximo y media.
El resultado final debe ser una serie con los estadísticos."""

In [32]:
##Inicializando listas a usar

lempleado = []
lsalario = []

##Solicitando al usuario que ingrese una cantidad valida de empleados

while True:
  try:
    total_empleados = int(input("Ingrese la cantidad de empleados que hay en la empresa: "))
    if type(total_empleados) == int and total_empleados > 0:
      break
    else:
      print("Ingrese un valor válido")
  except:
    print("Ingrese un valor válido")

##Realizando el llenado de las listas "lempleado" y "lsalario"

for counter_empleado in range(total_empleados):

  print("\n---EMPLEADO",counter_empleado+1)
  empleado = input("Ingrese el nombre del empleado: ")
  lempleado.append(empleado)


  while True:
    try:
      salario = float(input("Ingrese el salario del empleado: "))
      if type(precio) == float and salario > 0:
        lsalario.append(salario)
        break
      else:
        print("Ingrese un salario válido")
    except:
      print("Ingrese un salario válido")

print()
print(lempleado)
print(lsalario)

Ingrese la cantidad de empleados que hay en la empresa: 3

---EMPLEADO 1
Ingrese el nombre del empleado: Diego
Ingrese el salario del empleado: 1200

---EMPLEADO 2
Ingrese el nombre del empleado: Julio
Ingrese el salario del empleado: 1800

---EMPLEADO 3
Ingrese el nombre del empleado: Pablo
Ingrese el salario del empleado: 950.25

['Diego', 'Julio', 'Pablo']
[1200.0, 1800.0, 950.25]

In [33]:
##Importando el paquete pandas para la creacion del dataframe

import pandas as pd

##Creando el diccionario que contenga los datos del dataframe

info_salarial = {'Empleado':lempleado,'Salario':lsalario}

##Creando el dataframe con el listado de empleados y su salario asociado

df_info_salarial = pd.DataFrame(info_salarial)
df_info_salarial

  Empleado  Salario
0    Diego  1200.00
1    Julio  1800.00
2    Pablo   950.25

In [34]:
##Creando el resultado final

df_info_salarial.describe()

          Salario
count     3.00000
mean   1316.75000
std     436.73984
min     950.25000
25%    1075.12500
50%    1200.00000
75%    1500.00000
max    1800.00000

In [7]:
##----------------------------------------------------------------------------
##-----------------------------EJERCICIO 3------------------------------------
##----------------------------------------------------------------------------

In [8]:
##---------------------PARTE 1
"""Escribir programa que genere y muestre por pantalla un DataFrame
con los datos de la siguiente tabla:"""

'Escribir programa que genere y muestre por pantalla un DataFrame\ncon los datos de la siguiente tabla:'

In [39]:
##Creando listas con los datos de la tabla mostrada en la guia

lmeses = ['Enero','Febrero','Marzo','Abril','Mayo']
lventas = [30500,35600,28300,33900,42500]
lgastos = [22000,23450,18100,35700,32450]

ldatos = [lventas,lgastos]

##Importanto el paquete pandas para generar dataframe

import pandas as pd

##Creando DataFrame
index = ['Ventas','Gastos']

df_datos = pd.DataFrame(ldatos, index = index, columns = lmeses).transpose()
df_datos

##Agregando las nuevas columnas

         Ventas  Gastos
Enero     30500   22000
Febrero   35600   23450
Marzo     28300   18100
Abril     33900   35700
Mayo      42500   32450

In [ ]:
##---------------------PARTE 2
"""A continuación, generar nuevas columna:
1. Columna 1 = Gasto/Ventas*100.
2. Columna 2 = Si Ventas>= 30000, imprimir “Meta Superada”,
caso contrario imprimir “Meta no Superada”.
3. Columna 3 = Si Gasto>Ventas, calcular el sobre gasto.
4. Obtener el total de las ventas de los últimos 3 meses
5. Obtener el total de gastos de febrero a abril"""

In [40]:
##Importando paquete NumPy para crear las nuevas columnas a partir de operaciones matemáticas

import numpy as np

##Creando arrays a partir de las listas

np_lmeses = np.array(lmeses)
np_lventas = np.array(lventas)
np_lgastos = np.array(lgastos)

##Creando nuevas columnas a partir de los calculos

columna1 = (np_lgastos/np_lventas) * 100
columna2 = np.where(np_lventas >= 30000,"META SUPERADA","META NO SUPERADA")
columna3 = np.where(np_lgastos > np_lventas, np_lgastos - np_lventas, 0)

##Incorporando nuevas columnas

df_datos["columna1"] = columna1
df_datos["columna2"] = columna2
df_datos["columna3"] = columna3

df_datos

         Ventas  Gastos    columna1          columna2  columna3
Enero     30500   22000   72.131148     META SUPERADA         0
Febrero   35600   23450   65.870787     META SUPERADA         0
Marzo     28300   18100   63.957597  META NO SUPERADA         0
Abril     33900   35700  105.309735     META SUPERADA      1800
Mayo      42500   32450   76.352941     META SUPERADA         0

In [41]:
##Obteniendo el total de las ventas en los ultimos 3 meses

df_ventaslast3m = df_datos.tail(3)
ventaslast3m = np.sum(df_ventaslast3m["Ventas"])
print("El total de ventas en los ult 3 meses es:",ventaslast3m)

##Obteniendo el total de gastos de febrero a abril

fila_gastos = ["Febrero","Marzo","Abril"]

df_gastosmeses = np.sum(df_datos.loc[fila_gastos,"Ventas"])
df_gastosmeses
print("El total de gastos de febrero a abril es:",df_gastosmeses)

El total de ventas en los ult 3 meses es: 104700
El total de gastos de febrero a abril es: 97800

In [14]:
##----------------------------------------------------------------------------
##-----------------------------EJERCICIO 4------------------------------------
##----------------------------------------------------------------------------

In [ ]:
##---------------------PARTE 1
"""Con el siguiente fichero datos_seguros.csv contiene información
de riesgo de clientes de un banco. Escribir un programa con los
siguientes requisitos:
1. Generar un DataFrame con los datos del fichero."""

In [46]:
##Importando paquete pandas para la lectura de csv
import pandas as pd

##Obteniendo el contenido del archivo
df_datosseguro = pd.read_csv('/content/datos_seguro/datos_seguros.csv', sep=',')
df_datosseguro

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0,0.0,0.0,15.00,18.644.444,52.80,NaN,M,58,LIMA,0.000,0.000
1,201506,0,2.0,3215.0,3500.0,918.571,0.0,0.0,548.98,2632.02,5709.24,NaN,M,69,JUNIN,816.134,930.867
2,201506,0,1.0,3169.0,5000.0,6.338,0.0,0.0,0.00,4999,4999.00,0.0,M,16,CALLAO,1.000,1.000
3,201506,1,1.0,6495.0,8450.0,768.639,2.0,505.0,2137.94,4.900.191.666,11206.80,NaN,F,62,LIMA,413.831,505.504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.37,12.37,NaN,F,5,AREQUIPA,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45793,201505,0,2.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,0.0,F,4,LIMA,0.000,0.000
45794,201505,0,NaN,NaN,NaN,NaN,2.0,6189.0,1314.10,1314.1,1314.10,NaN,F,76,LA LIBERTAD,0.000,0.000
45795,201506,0,NaN,NaN,NaN,NaN,1.0,138.0,36.00,73.114.285,220.00,NaN,F,20,LIMA,0.000,0.000
45796,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,0.00,29.946.875,830.00,0.0,M,23,PIURA,0.000,0.000
45797,201506,0,1.0,0.0,0.0,0,6.0,2762.0,0.00,780,780.00,0.0,M,125,PASCO,0.000,0.000

In [47]:
##---------------------PARTE 2
"""Mostrar por pantalla las dimensiones del DataFrame, el
número de datos que contiene, los nombres de sus columnas
y filas, los tipos de datos de las columnas"""

##Motrando la dimensión del dataframe
print("Dimensiones del dataframe:")
print(df_datosseguro.shape)
print("\n")

#Mostrando los nombres de las filas y columnas
print("Nombres de las columnas:\n")
print(df_datosseguro.columns)
print("\n")
print("Nombres de las filas:\n")
print(df_datosseguro.index)
print("\n")

##Mostrando los tipos de datos de las columnas
print("Tipo de datos de las columnas:\n")
print(df_datosseguro.info())

Dimensiones del dataframe:
(45798, 17)


Nombres de las columnas:

Index(['MES_T0', 'VENTA_SEGURO', 'NUM_TC_TOTAL_T2', 'SALDO_BCO_T2',
       'LINEA_BCO_T2', 'USO_LINEA_BCO_T2', 'Nro_CTa_Ahorro_Bco_T1',
       'Ahorro_Sldo_Bco_T1', 'monto_ope_t2', 'PROM_ANUAL_MTO_OPERA',
       'MAX_MTO_OPERA_Anual', 'Ratio_HospvsMtoTotal_t2', 'SEXO',
       'ANTIGUEDAD_MES', 'DEPARTAMENTO', 'SOW_BCO_T2', 'SOW_BCO_SEMESTRAL'],
      dtype='object')


Nombres de las filas:

RangeIndex(start=0, stop=45798, step=1)


Tipo de datos de las columnas:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45798 entries, 0 to 45797
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   MES_T0                   45798 non-null  int64
 1   VENTA_SEGURO             45798 non-null  int64
 2   NUM_TC_TOTAL_T2          25397 non-null  float64
 3   SALDO_BCO_T2             25452 non-null  float64
 4   LINEA_BCO_T2             25452 non-null  float64
 5   USO_LINEA_BCO_T2         25452 non-null  object
 6   Nro_CTa_Ahorro_Bco_T1    44405 non-null  float64
 7   Ahorro_Sldo_Bco_T1       44405 non-null  float64
 8   monto_ope_t2             32927 non-null  float64
 9   PROM_ANUAL_MTO_OPERA     32927 non-null  object
 10  MAX_MTO_OPERA_Anual      32927 non-null  float64
 11  Ratio_HospvsMtoTotal_t2  29719 non-null  float64
 12  SEXO                     45798 non-null  object
 13  ANTIGUEDAD_MES           45798 non-null  int64
 14  DEPARTAMENTO             45798 non-null  object
 15  SOW_BCO_T2               45798 non-null  float64
 16  SOW_BCO_SEMESTRAL        45798 non-null  float64
dtypes: float64(10), int64(3), object(4)
memory usage: 5.9+ MB
None

In [48]:
"""Mostrar las 10
primeras filas y las 10 últimas filas, verificar si tiene datos
perdidos/nulos."""

##Mostrando las 10 primeras filas
print("Priemras 10 filas:\n")
print(df_datosseguro.head(10))

Priemras 10 filas:

   MES_T0  VENTA_SEGURO  NUM_TC_TOTAL_T2  SALDO_BCO_T2  LINEA_BCO_T2  \
0  201506             0              3.0           0.0        2300.0
1  201506             0              2.0        3215.0        3500.0
2  201506             0              1.0        3169.0        5000.0
3  201506             1              1.0        6495.0        8450.0
4  201506             0              NaN           NaN           NaN
5  201506             0              3.0        2373.0        9373.0
6  201506             0              2.0           0.0           0.0
7  201506             0              1.0        3023.0       16720.0
8  201506             0              1.0        1931.0       12500.0
9  201506             0              NaN           NaN           NaN

  USO_LINEA_BCO_T2  Nro_CTa_Ahorro_Bco_T1  Ahorro_Sldo_Bco_T1  monto_ope_t2  \
0                0                    0.0                 0.0         15.00
1          918.571                    0.0                 0.0        548.98
2            6.338                    0.0                 0.0          0.00
3          768.639                    2.0               505.0       2137.94
4              NaN                    0.0                 0.0         12.37
5          253.174                    0.0                 0.0        411.86
6                0                    1.0              2662.0         46.00
7          180.801                    0.0                 0.0       2982.90
8           15.448                    0.0                 0.0        412.00
9              NaN                    2.0             40718.0       1644.30

  PROM_ANUAL_MTO_OPERA  MAX_MTO_OPERA_Anual  Ratio_HospvsMtoTotal_t2 SEXO  \
0           18.644.444                52.80                      NaN    M
1              2632.02              5709.24                      NaN    M
2                 4999              4999.00                      0.0    M
3        4.900.191.666             11206.80                      NaN    F
4                12.37                12.37                      NaN    F
5        1.410.662.727              5055.62                      NaN    M
6          218.393.333               390.90                      NaN    M
7        1.721.769.166              3137.70                      0.0    M
8            9.863.375              2119.00                      NaN    M
9            1.581.335              3565.14                      NaN    F

   ANTIGUEDAD_MES DEPARTAMENTO  SOW_BCO_T2  SOW_BCO_SEMESTRAL
0              58         LIMA       0.000              0.000
1              69        JUNIN     816.134            930.867
2              16       CALLAO       1.000              1.000
3              62         LIMA     413.831            505.504
4               5     AREQUIPA       0.000              0.000
5              44       CALLAO     181.633            677.393
6               4         LIMA       0.000              0.000
7             136         LIMA       1.000              1.000
8             292         LIMA     278.603            541.839
9              49     AREQUIPA       0.000              0.000

In [49]:
"""Mostrar las 10
primeras filas y las 10 últimas filas, verificar si tiene datos
perdidos/nulos."""

##Mostrando las 10 ultimas filas
print("Priemras 10 filas:\n")
print(df_datosseguro.tail(10))

Priemras 10 filas:

       MES_T0  VENTA_SEGURO  NUM_TC_TOTAL_T2  SALDO_BCO_T2  LINEA_BCO_T2  \
45788  201505             0              4.0           0.0           0.0
45789  201505             0              1.0           0.0           0.0
45790  201505             0              2.0           0.0           0.0
45791  201506             0              1.0           0.0           0.0
45792  201505             0              2.0           0.0       12000.0
45793  201505             0              2.0           0.0           0.0
45794  201505             0              NaN           NaN           NaN
45795  201506             0              NaN           NaN           NaN
45796  201506             0              NaN           NaN           NaN
45797  201506             0              1.0           0.0           0.0

      USO_LINEA_BCO_T2  Nro_CTa_Ahorro_Bco_T1  Ahorro_Sldo_Bco_T1  \
45788                0                    0.0                 0.0
45789                0                    2.0              8217.0
45790                0                    0.0                 0.0
45791                0                    2.0              9261.0
45792                0                    2.0               804.0
45793                0                    NaN                 NaN
45794              NaN                    2.0              6189.0
45795              NaN                    1.0               138.0
45796              NaN                    0.0                 0.0
45797                0                    6.0              2762.0

       monto_ope_t2 PROM_ANUAL_MTO_OPERA  MAX_MTO_OPERA_Anual  \
45788       1054.41              688.975              1054.41
45789          0.00                681.6              1337.00
45790        810.00                  810               810.00
45791       4244.19           34.661.625             15419.30
45792        277.20                237.6               277.20
45793           NaN                  NaN                  NaN
45794       1314.10               1314.1              1314.10
45795         36.00           73.114.285               220.00
45796          0.00           29.946.875               830.00
45797          0.00                  780               780.00

       Ratio_HospvsMtoTotal_t2 SEXO  ANTIGUEDAD_MES DEPARTAMENTO  SOW_BCO_T2  \
45788                      NaN    F             105         LIMA         0.0
45789                      0.0    M              31       ANCASH         0.0
45790                      NaN    M             226         LIMA         0.0
45791                      0.0    F             204      UCAYALI         0.0
45792                      NaN    M               8  LA LIBERTAD         0.0
45793                      0.0    F               4         LIMA         0.0
45794                      NaN    F              76  LA LIBERTAD         0.0
45795                      NaN    F              20         LIMA         0.0
45796                      0.0    M              23        PIURA         0.0
45797                      0.0    M             125        PASCO         0.0

       SOW_BCO_SEMESTRAL
45788                0.0
45789                0.0
45790                0.0
45791                0.0
45792                0.0
45793                0.0
45794                0.0
45795                0.0
45796                0.0
45797                0.0

In [50]:
"""verificar si tiene datos
perdidos/nulos."""

##Verificando si existen datos perdidos en el dataset
df_datosseguro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45798 entries, 0 to 45797
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   MES_T0                   45798 non-null  int64
 1   VENTA_SEGURO             45798 non-null  int64
 2   NUM_TC_TOTAL_T2          25397 non-null  float64
 3   SALDO_BCO_T2             25452 non-null  float64
 4   LINEA_BCO_T2             25452 non-null  float64
 5   USO_LINEA_BCO_T2         25452 non-null  object
 6   Nro_CTa_Ahorro_Bco_T1    44405 non-null  float64
 7   Ahorro_Sldo_Bco_T1       44405 non-null  float64
 8   monto_ope_t2             32927 non-null  float64
 9   PROM_ANUAL_MTO_OPERA     32927 non-null  object
 10  MAX_MTO_OPERA_Anual      32927 non-null  float64
 11  Ratio_HospvsMtoTotal_t2  29719 non-null  float64
 12  SEXO                     45798 non-null  object
 13  ANTIGUEDAD_MES           45798 non-null  int64
 14  DEPARTAMENTO             45798 non-null  object
 15  SOW_BCO_T2               45798 non-null  float64
 16  SOW_BCO_SEMESTRAL        45798 non-null  float64
dtypes: float64(10), int64(3), object(4)
memory usage: 5.9+ MB

In [51]:
##Extrayendo la cantidad de records en una lista
records = df_datosseguro.shape[0]

rows = [records for column in df_datosseguro.columns]
rows

##Presentando la cantidad de registros, registros no null y registros null

df_nulldata = df_datosseguro.isnull().sum()
# np_df_nulldata = pd.array(df_nulldata)

df_notnulldata = df_datosseguro.notnull().sum()
# np_df_notnulldata = pd.array(df_notnulldata)


df_nullvalues = pd.DataFrame({"Records":rows,"Notnull records":df_notnulldata,"Null records":df_nulldata})
df_nullvalues

                         Records  Notnull records  Null records
MES_T0                     45798            45798             0
VENTA_SEGURO               45798            45798             0
NUM_TC_TOTAL_T2            45798            25397         20401
SALDO_BCO_T2               45798            25452         20346
LINEA_BCO_T2               45798            25452         20346
USO_LINEA_BCO_T2           45798            25452         20346
Nro_CTa_Ahorro_Bco_T1      45798            44405          1393
Ahorro_Sldo_Bco_T1         45798            44405          1393
monto_ope_t2               45798            32927         12871
PROM_ANUAL_MTO_OPERA       45798            32927         12871
MAX_MTO_OPERA_Anual        45798            32927         12871
Ratio_HospvsMtoTotal_t2    45798            29719         16079
SEXO                       45798            45798             0
ANTIGUEDAD_MES             45798            45798             0
DEPARTAMENTO               45798            45798             0
SOW_BCO_T2                 45798            45798             0
SOW_BCO_SEMESTRAL          45798            45798             0

In [52]:
##---------------------PARTE 3
"""Extraer las 1000 primeras filas y almacenarlas en un
contenedor"""

##Mostrando las 1000 primeras filas

df_primerasmil = df_datosseguro.head(1000)